package dev.typeracist.typeracist.logic.characters;

public enum SkillActivationOnState {
    ACTIVATION_BEFORE_ATTACK,
    ACTIVATION_ON_ATTACK,
    ACTIVATION_AFTER_ATTACK,
    ACTIVATION_BEFORE_ITEM,
    ACTIVATION_AFTER_ITEM,
    ACTIVATION_BEFORE_DEFENSE,
    ACTIVATION_ON_DEFENSE,
    ACTIVATION_AFTER_DEFENSE,
    ACTIVATION_ALWAYS
}
